trigger:
  paths:
    include:
      - generators/
      - templates/
      - eng/pipelines/repoman.yml
  branches:
    include:
      - main

pr:
  paths:
    include:
      - generators/
      - templates/
      - eng/pipelines/repoman.yml

variables:
  skipComponentGovernanceDetection: true

stages:
  - stage: Validation
    jobs:
      - job: TEST
        steps:
          - pwsh: Write-Host foobar2
            displayName: TEST
