trigger:
  paths:
    include:
      - generators/
      - templates/
      - eng/pipelines/repoman.yml
  branches:
    include:
      - main

pr:
  paths:
    include:
      - generators/
      - templates/
      - eng/pipelines/repoman.yml

stages:
  - stage: Validation
    jobs:
      - job: TEST
        steps:
          - pwsh: Write-Host foobar
            displayName: TEST
