name: templates-ci

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - "templates/**"
      - ".github/workflows/templates-ci.yml"

jobs:
  cspell-lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo foobar
